### ISSUE TITLE
text() is now broken

### ISSUE THREAD

**Issue by andreisusanu** [oleghalin/nova-link-field#10]
Hello, text() was broken on the last release (v1.2.3), when using function() {return 'custom';}.

This is where the bug was introduced:
![image](https://user-images.githubusercontent.com/2534555/83227794-ae014180-a18d-11ea-9ec5-d1b981f78019.png)

Please check it out. v1.2.2 works fine!

**Comment by JohnRoux** [comment]
Confirmed.
![Screenshot from 2020-08-24 18-07-50](https://user-images.githubusercontent.com/4610241/91068581-ce2d8900-e634-11ea-89c4-43e88eb86448.png)
![Screenshot from 2020-08-24 18-07-31](https://user-images.githubusercontent.com/4610241/91068586-cf5eb600-e634-11ea-81f9-6909cf1a9022.png)

**Comment by JohnRoux** [comment]
Can we push a new tag (1.2.4) for this as well :)
