### ISSUE TITLE
Exceptions when updating

### ISSUE THREAD

**Issue by bilogic** [oleghalin/nova-link-field#13]
I have an foreign key, e.g. `customer_id` and want to provide a link the the relevant resource. It works when viewing etc, but throws exception when doing an update.

```PHP

Link::make('Customer')
    ->url(function () {
        // this line throws an exception of "Trying to get property 'customer' of non-object"
        return "/admin/resources/customers/{$this->customer->id}"; 
    })
    ->text(function () {
        return $this->customer->name;
    }),
```

**Comment by oleghalin** [comment]
@bilogic use `optional()` helper to solve this. 

```
    ->url(function () {
$key = optional($this->customer)->id};
        return "/admin/resources/customers/{$key}"; 
    })
```

**Comment by bilogic** [comment]
@oleghalin 

Why is `url()` called during an update? Can the field not call it during an update?

**Comment by oleghalin** [comment]
@bilogic `fields()` method will be called at any Nova Request method (GET, POST, PUT). It is not Field control layer, its your Nova application layer

**Comment by bilogic** [comment]
@oleghalin 

What I meant is, for a Nova `Text` field, if I write `$this->customer->id` in `->displayAs(...)`, it doesn't throw an exception during update.

Can the `Link::url(...)` and `Link::text(...)` behave the same way?
